### ISSUE TITLE
Report Generating Module

### ISSUE THREAD

**Issue by Cdingram** [C391W15/C391W15#3]
This module will be used by a system administrator to get the list of all patients with a specified diagnosis for a given time period. For each patient, the list must contain the name, address and phone number of the patient, and testing date of the first radiology record that contains the specified diagnosis. For example, a system administrator shall be able to use this tool to generate the list of all patients who have been diagnosed having breast cancer in 2014.

**Comment by aktse** [comment]
https://github.com/C391W15/C391W15/commit/aafe40e8c166974a51bdbcde4a97f0862a362aa4
